-- Supabase BioLink schema
-- Safe to run multiple times

-- Extensions
create extension if not exists pgcrypto;

-- Tables
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  handle text unique not null check (handle ~ '^[a-z0-9][a-z0-9-_]{1,30}$'),
  display_name text,
  avatar_url text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.link_lists (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references public.profiles(id) on delete cascade,
  slug text not null,
  title text,
  description text,
  avatar_url text,
  theme jsonb default '{}'::jsonb,
  socials jsonb default '{}'::jsonb,
  layout text default 'buttons',
  visibility text default 'public',
  passkey_hash text,
  is_enabled boolean default true,
  timezone text default 'local',
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  unique (owner_id, slug)
);

create table if not exists public.link_items (
  id uuid primary key default gen_random_uuid(),
  list_id uuid not null references public.link_lists(id) on delete cascade,
  title text not null,
  url text not null,
  image_url text,
  order_index integer not null default 0,
  is_active boolean default true,
  schedule_start timestamptz,
  schedule_end timestamptz,
  utm jsonb default '{}'::jsonb,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index if not exists link_items_list_idx on public.link_items(list_id);
create index if not exists link_items_order_idx on public.link_items(list_id, order_index);

create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  list_id uuid not null references public.link_lists(id) on delete cascade,
  link_id uuid references public.link_items(id) on delete set null,
  type text not null check (type in ('impression','click')),
  occurred_at timestamptz not null default now()
);

create index if not exists analytics_events_list_idx on public.analytics_events(list_id, occurred_at);
create index if not exists analytics_events_link_idx on public.analytics_events(link_id, occurred_at);

-- Buckets (create via UI if this fails due to permissions)
insert into storage.buckets (id, name, public) values ('avatars','avatars', true)
on conflict (id) do nothing;
insert into storage.buckets (id, name, public) values ('media','media', true)
on conflict (id) do nothing;

-- RLS
alter table public.profiles enable row level security;
alter table public.link_lists enable row level security;
alter table public.link_items enable row level security;
alter table public.analytics_events enable row level security;

-- Policies
create policy if not exists "profiles_select_all"
  on public.profiles for select using (true);

create policy if not exists "profiles_insert_self"
  on public.profiles for insert
  with check ((select auth.uid()) = id);

create policy if not exists "profiles_update_self"
  on public.profiles for update
  using ((select auth.uid()) = id);

create policy if not exists "lists_select_public_or_owner"
  on public.link_lists for select
  using (visibility in ('public','unlisted') or owner_id = (select auth.uid()));

create policy if not exists "lists_insert_owner_only"
  on public.link_lists for insert
  with check (owner_id = (select auth.uid()));

create policy if not exists "lists_update_owner_only"
  on public.link_lists for update
  using (owner_id = (select auth.uid()));

create policy if not exists "lists_delete_owner_only"
  on public.link_lists for delete
  using (owner_id = (select auth.uid()));

create policy if not exists "items_select_public_or_owner"
  on public.link_items for select
  using (
    exists (
      select 1 from public.link_lists ll
      where ll.id = list_id
        and (ll.visibility in ('public','unlisted') or ll.owner_id = (select auth.uid()))
    )
  );

create policy if not exists "items_insert_owner_only"
  on public.link_items for insert
  with check (
    exists (
      select 1 from public.link_lists ll
      where ll.id = list_id and ll.owner_id = (select auth.uid())
    )
  );

create policy if not exists "items_update_owner_only"
  on public.link_items for update
  using (
    exists (
      select 1 from public.link_lists ll
      where ll.id = list_id and ll.owner_id = (select auth.uid())
    )
  );

create policy if not exists "items_delete_owner_only"
  on public.link_items for delete
  using (
    exists (
      select 1 from public.link_lists ll
      where ll.id = list_id and ll.owner_id = (select auth.uid())
    )
  );

create policy if not exists "analytics_insert_any"
  on public.analytics_events for insert with check (true);

create policy if not exists "analytics_select_owner_lists"
  on public.analytics_events for select
  using (
    exists (
      select 1 from public.link_lists ll
      where ll.id = list_id and ll.owner_id = (select auth.uid())
    )
  );




